export const ESTABLECIMIENTOS = [
    "Algar S.A",
    "Alicura",
    "Bey Malek",
    "Bucalemu",
    "Cabeza De Zorro",
    "Cajon De Hualcupen Y Los Ñires",
    "Calcatre S.A",
    "Caminos Rural",
    "Estancia Cerro De Los Pinos",
    "Collunco",
    "Collon Cura",
    "Los Manantiales De Collon Cura",
    "Donap S.R.L",
    "Dove Outfitters Srl",
    "El Cerrito",
    "El Recuerdo",
    "El Refugio",
    "El Refugio Quillen",
    "Estancia El Rincón",
    "Estancia Argentina Moquehue Neuquen",
    "Estancia Caleufu",
    "Estancia Chimehuin",
    "Estancia Los Helechos",
    "Estancia Los Lirios",
    "Estancia Paylacura",
    "Estancia Pilolil",
    "Estancia Quilachanquil",
    "Estancia Rahue",
    "Estancia Santa Isabel",
    "Estancias Del Kilka S.A",
    "Estancias Los Peucos Y Los Ranchos",
    "Estancia Huechahue",
    "Junin De Los Andes",
    "La Belisle",
    "Estancia Belisle",
    "La Gabcia",
    "Estancia La Gotera",
    "Estancia La María Juana",
    "La Mimi",
    "La Querencia",
    "La Rinconada S.A",
    "Estancia La Rinconada",
    "Lago Machónico",
    "Ea. Lago Machonico",
    "Estancia Las Breñas",
    "Los Remolinos",
    "Mamuil Malal",
    "Nahuel Mapi",
    "Palitue",
    "Parque Diana",
    "Estancia Quillen",
    "Ruta 52 Y Ruta 40",
    "Estancia San Juan",
    "Estancia San Pedro",
    "Estancia Santa Lucia",
    "Estancia Santa Rosa",
    "Sihuen",
    "Estancia Toki Eder",
    "Estancia Tres Rios",
    "Zona Andina Sur",
    "Casa De Lata Criadero",
    "Estancia Casa De Lata",
    "Ea. Chacabuco",
    "Las Pircas",
    "Estancia Tipiliuke"
];
